"""Updated table name

Revision ID: 54b69f70e7b3
Revises: 
Create Date: 2022-04-12 08:17:01.602463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


# revision identifiers, used by Alembic.
revision = '54b69f70e7b3'
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(), nullable=False),
                    sa.Column('description', sa.VARCHAR(), nullable=True),
                    sa.Column('date', sa.DATE(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), nullable=False, unique=False, server_default=expression.false(), default=True))
    # ### end Alembic commands ###
